name: zip-3d-parts
on:
  push:
    branches:
      - main
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: '3d parts/'
          dest: '3d parts.zip'
