name: zip-3d-parts
on:
  push:
    branches:
      - main
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: 3d_parts/
          recursive: true
          dest: 3d_parts.zip
      - name: Commit results
        run: |
          git config --global user.name "Github zip-3d-parts action"
          git config --global user.email "nobody@nomail.net"
          git add 3d_parts.zip
          git commit -m 'Re-build 3d_parts.zip' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
