name: update-readme
on:
  push:
    branches:
      - main
jobs:
  copy-readme-from-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp docs/index.md README.md
