name: update-readme
on:
  push:
    branches:
      - main
jobs:
  copy-readme-from-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy from docs
      - run: cp docs/index.md README.md
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
