name: zip-3d-parts
on:
  push:
    branches:
      - main
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: "3d parts/"
          recursive: false
          dest: "3d parts.zip"
      - name: Commit results
        run: |
          git config --global user.name "Github zip-3d-parts action"
          git config --global user.email "nobody@nomail.net"
          git add '3d parts.zip'
          git commit '3d parts.zip' -m 'Re-build "3d parts.zip"' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
